### PR TITLE
Added power support for the travis.yml file with ppc64le

### PR DESCRIPTION
**Pull request by sreekanth370**
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. 
This helps us simplify testing later when distributions are re-building and re-releasing.

### CODE REVIEW

**Comment by sreekanth370** [comment]
For more info tag @gerrith3

**Comment by phated** [comment]
@gerrith3 tell your employees to stop opening these on @gulpjs repositories. We are migrating to GH Actions and they don't support your architecture.

**Comment by gerrith3** [comment]
@phated Will do.  BTW when we have GH Actions support for ppc64le would you be open to enabling this?  Or are you opposed to having any customers on Linux on Power?

**Comment by phated** [comment]
If we can "have our cake and eat it" (use GH Actions with Power support **and** it doesn't cause us to pay for CI), we will consider adding it as a supported architecture in our build matrix.

**Comment by gerrith3** [comment]
We can guarantee you won't have to pay for Travis on Power - we donated all the hardware resources for that.  No idea yet what the model will be with GHA, though. I believe you are currently limited to 2000 minutes but I don't know what their future plans are for open source.

**Pull request closed without merging**
